notifications:
  email: false
sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install .
script:
  - flake8 civis_jupyter_notebooks
  - pytest -vv civis_jupyter_notebooks
  - |
    if [ ${TRAVIS_PYTHON_VERSION} = 3.6 ]
    then
        ./tests/run_docker_tests.sh tests/python3/Dockerfile
    fi
  - |
    if [ ${TRAVIS_PYTHON_VERSION} = 2.7 ]
    then
        ./tests/run_docker_tests.sh tests/python2/Dockerfile
    fi
